[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "13.0.0"
regex = "1.10.2"
fnv = "1.0.7"
itertools = "0.12.0"

[dev-dependencies]
rand = "0.8.5"
