all: build

step0:
	cargo build --release --bin step0_repl

step1:
	cargo build --release --bin step1_read_print

step2:
	cargo build --release --bin step2_eval

step3:
	cargo build --release --bin step3_env

step4:
	cargo build --release --bin step4_if_fn_do

step5:
	cargo build --release --bin step5_tco

step6:
	cargo build --release --bin step6_file

build:
	cargo build --release

.PHONY: clean
clean:
	cargo clean